version: "3.8"
   
services:
    web:
        build: .
        container_name: BlogProject
        command: python manage.py runserver 127.0.0.1:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        environment:
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_USER=new_blog
            - SQL_PASSWORD=blog123
            - SQL_HOST=db
            - SQL_PORT=5432
            - DATABASE=postgres
        entrypoint: 
            /entrypoint.sh
        depends_on:
            - db

    db:
        image: postgres:13.0-alpine
        volumes:
            - BlogProject:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=new_blog
            - POSTGRES_USER=new_blog
            - POSTGRES_PASSWORD=blog123
        ports:
            - "5432:5432"

volumes:
    BlogProject:

    